### ISSUE TITLE
errors and junk,

### ISSUE THREAD

**Issue by shakyevan444** [filtitov2001/WeatherApp#2]
<img width="517" alt="CleanShot 2022-10-11 at 01 04 07@2x" src="https://user-images.githubusercontent.com/84460058/195001398-565e1bd3-d7ec-42b5-a597-a425bd21d32b.png">

**Comment by thefiltitoff** [comment]
🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️
You need to install pods by ```pod install``` command and open .xcworkspace file.
